### ISSUE TITLE
Sample Collection link broken in readme

### ISSUE THREAD

**Issue by myutzy** [bconner/Epicor-Rest-PostmanSamples#1]
The "Sample Collection" link in the readme (http://epichub/epicor-erp/rest-developer-materials/blob/master/samples/postman/Erp10RestSamples.json.postman_collection) isn't working. Do you have an updated link to download the postman collection? Thanks!

![image](https://user-images.githubusercontent.com/1199572/40561464-647cd696-602b-11e8-91f8-0bfef14e24cf.png)

**Comment by bconner** [comment]
The postman collection is in this repository side by side with this readme soo you can either download the whole repository here or navigate right to the postman collection file which is [here](https://raw.githubusercontent.com/bconner/Epicor-Rest-PostmanSamples/master/Erp10RestSamples.json.postman_collection)

I've also updated the readme link which pointed to where we host this inside our private network by mistake. thanks for pointing it out.
